import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const courseMasterSource = readFileSync(
  new URL(
    "../../app/components/center_factory/TrainingCourseManagement/modules/CourseMasterWorkspace.tsx",
    import.meta.url,
  ),
  "utf8",
);

describe("Course Master form linking contract", () => {
  it("guides users through required course setup fields", () => {
    expect(courseMasterSource).toContain("Course setup guideline");
    expect(courseMasterSource).toContain("requiredCourseValues");
    expect(courseMasterSource).toContain("completedRequiredFields");
    expect(courseMasterSource).toContain("isCourseFormReady");
    expect(courseMasterSource).toContain("Required field completion");
    expect(courseMasterSource).toContain(
      "Generated by the server when saved",
    );
    expect(courseMasterSource).toContain("disabled={!isCourseFormReady}");
  });

  it("stores stable IDs and legacy display names for all four form links", () => {
    expect(courseMasterSource).toContain("preTestId");
    expect(courseMasterSource).toContain("postTestId");
    expect(courseMasterSource).toContain("evaluationId");
    expect(courseMasterSource).toContain("evaluationAfter30DayId");
    expect(courseMasterSource).toContain("handleAssessmentSelection");
    expect(courseMasterSource).toContain("handleEvaluationSelection");
  });

  it("loads only published form options from the real assessment/evaluation APIs", () => {
    expect(courseMasterSource).toContain("listAssessments(");
    expect(courseMasterSource).toContain("listEvaluations(");
    expect(courseMasterSource).toContain('status: "ACTIVE"');
    expect(courseMasterSource).toContain('status: "PUBLISHED"');
    expect(courseMasterSource).toContain(
      "const publishedPreTests = assessmentOptions;",
    );
    expect(courseMasterSource).toContain(
      "const publishedPostTests = assessmentOptions;",
    );
  });

  it("allows manual links as an alternative to published forms", () => {
    expect(courseMasterSource).toContain("preTestLink");
    expect(courseMasterSource).toContain("postTestLink");
    expect(courseMasterSource).toContain("evaluationLink");
    expect(courseMasterSource).toContain("evaluationAfter30DayLink");
    expect(courseMasterSource).toContain("handleFormLinkChange");
    expect(courseMasterSource).toContain('placeholder="Paste pre-test form link"');
    expect(courseMasterSource).toContain('placeholder="Paste post-test form link"');
    expect(courseMasterSource).toContain('placeholder="Paste evaluation form link"');
    expect(courseMasterSource).toContain('placeholder="Paste 30-day evaluation form link"');
    expect(courseMasterSource).toContain("Manual form link will be used.");
  });

  it("keeps After Training and After 30 Days evaluations as separate, non-interchangeable forms", () => {
    expect(courseMasterSource).toContain(
      'evaluation.timing === "After Training"',
    );
    expect(courseMasterSource).toContain(
      'evaluation.timing === "30-Day Follow-up"',
    );
  });

  it("keeps course group values in English while localizing the placeholder", () => {
    expect(courseMasterSource).toContain(
      '<option value="">Select Course Group</option>',
    );
    expect(courseMasterSource).toContain(
      '<option key={group} value={group} translate="no">{group}</option>',
    );
  });
});
