USE [TrainingPlanManagementDB];
GO

SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
GO

BEGIN TRY
  BEGIN TRANSACTION;

  IF OBJECT_ID(N'dbo.CK_audit_log_category', N'C') IS NOT NULL
  BEGIN
    ALTER TABLE dbo.audit_log DROP CONSTRAINT CK_audit_log_category;
  END;

  ALTER TABLE dbo.audit_log ADD CONSTRAINT CK_audit_log_category
    CHECK (category IN (N'AUTH', N'PII', N'DELETE', N'ACCOUNT', N'EXPORT', N'CREATE', N'UPDATE', N'ACTIVITY'));

  COMMIT TRANSACTION;
END TRY
BEGIN CATCH
  IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
  THROW;
END CATCH;
GO
