import { ApiError } from "../api/errors";
import type { AuthenticatedPrincipal } from "../auth/types";
import { employeeRepository,type EmployeeRepository } from "./repository";
import { protectNationalId,revealNationalId } from "./nationalId";
import type { EmployeeInput,EmployeeListFilters,UpdateEmployeeInput } from "./types";
const denied=()=>new ApiError({code:"EMPLOYEE_SCOPE_DENIED",message:"Employee is outside your permitted scope",status:403});
const missing=()=>new ApiError({code:"EMPLOYEE_NOT_FOUND",message:"Employee not found",status:404});
export const createEmployeeService=(repo:EmployeeRepository=employeeRepository)=>({
  list:(p:AuthenticatedPrincipal,f:EmployeeListFilters)=>repo.list(p,f),
  async get(p:AuthenticatedPrincipal,id:string){const r=await repo.findById(id);if(!r)throw missing();if(p.role==="HRD_FACTORY"&&r.companyId!==p.companyId)throw denied();return r},
  async create(p:AuthenticatedPrincipal,input:EmployeeInput){const companyId=p.role==="HRD_FACTORY"?p.companyId:input.companyId;if(!companyId)throw denied();const i={...input,companyId};const protectedId=protectNationalId(i.nationalId);if(!await repo.referencesExist(i))throw new ApiError({code:"INVALID_REFERENCE",message:"Company or employee master reference is invalid",status:409});if(await repo.conflict(companyId,i.employeeCode,protectedId.hash))throw new ApiError({code:"EMPLOYEE_CONFLICT",message:"Employee code or National ID already exists",status:409});return repo.create(i,protectedId)},
  async update(p:AuthenticatedPrincipal,id:string,u:UpdateEmployeeInput){const current=await repo.findById(id);if(!current)throw missing();if(p.role==="HRD_FACTORY"&&current.companyId!==p.companyId)throw denied();const bundle=await repo.bundle(id);let nationalId=u.nationalId;if(!nationalId){if(!bundle?.national_id_encrypted||!bundle.national_id_key_version)throw new ApiError({code:"NATIONAL_ID_REQUIRED",message:"Enter a valid 13-digit National ID before saving this employee",status:400});nationalId=revealNationalId(bundle.national_id_encrypted,bundle.national_id_key_version)}const i:EmployeeInput={companyId:p.role==="HRD_FACTORY"?p.companyId!:u.companyId??current.companyId,employeeCode:u.employeeCode??current.employeeCode,functionId:u.functionId===undefined?current.functionId:u.functionId,divisionId:u.divisionId===undefined?current.divisionId:u.divisionId,departmentId:u.departmentId===undefined?current.departmentId:u.departmentId,sectionId:u.sectionId===undefined?current.sectionId:u.sectionId,positionId:u.positionId===undefined?current.positionId:u.positionId,levelId:u.levelId===undefined?current.levelId:u.levelId,nationalId,titleTh:u.titleTh===undefined?current.titleTh:u.titleTh,titleEn:u.titleEn===undefined?current.titleEn:u.titleEn,firstNameTh:u.firstNameTh??current.firstNameTh,lastNameTh:u.lastNameTh??current.lastNameTh,firstNameEn:u.firstNameEn===undefined?current.firstNameEn:u.firstNameEn,lastNameEn:u.lastNameEn===undefined?current.lastNameEn:u.lastNameEn,birthDate:u.birthDate===undefined?current.birthDate:u.birthDate,hireDate:u.hireDate===undefined?current.hireDate:u.hireDate,telephone:u.telephone===undefined?current.telephone:u.telephone,email:u.email===undefined?current.email:u.email,employmentStatus:u.employmentStatus??current.employmentStatus};const protectedId=protectNationalId(nationalId);if(!await repo.referencesExist(i))throw new ApiError({code:"INVALID_REFERENCE",message:"Employee master reference is invalid",status:409});if(await repo.conflict(i.companyId,i.employeeCode,protectedId.hash,id))throw new ApiError({code:"EMPLOYEE_CONFLICT",message:"Employee code or National ID already exists",status:409});return repo.update(id,i,protectedId)},
  async remove(p:AuthenticatedPrincipal,id:string){const current=await repo.findById(id);if(!current)throw missing();if(p.role==="HRD_FACTORY"&&current.companyId!==p.companyId)throw denied();try{return await repo.delete(id)}catch(e:unknown){if(e instanceof ApiError&&e.code==="INVALID_REFERENCE")throw new ApiError({code:"EMPLOYEE_IN_USE",message:"Employee is in use; set status to INACTIVE instead",status:409});throw e}},
  async reveal(p:AuthenticatedPrincipal,id:string){const b=await repo.bundle(id);if(!b)throw missing();let allowed=p.role==="HRD_CENTER"||(p.role==="EMPLOYEE"&&p.employeeId===id)||(p.role==="HRD_FACTORY"&&p.companyId===String(b.company_id));if(!allowed&&p.role==="HRD_FACTORY"&&p.companyId)allowed=await repo.factoryTrainingAccess(id,p.companyId);if(!allowed)throw denied();if(!b.national_id_encrypted||!b.national_id_key_version)throw new ApiError({code:"NATIONAL_ID_UNAVAILABLE",message:"National ID is unavailable",status:404});return{nationalId:revealNationalId(b.national_id_encrypted,b.national_id_key_version)}}});
export const employeeService=createEmployeeService();export type EmployeeService=ReturnType<typeof createEmployeeService>;
