export const ROLE_CODES = ["EMPLOYEE", "HRD_FACTORY", "HRD_CENTER", "ADMIN"] as const;

export type RoleCode = (typeof ROLE_CODES)[number];

export type AuthenticationAccount = {
  userId: string;
  username: string;
  passwordHash: string;
  accountStatus: string;
  roleCode: string;
  roleStatus: string;
  employeeId: string | null;
  employeeUserId: string | null;
  employeeStatus: string | null;
  employeeCompanyId: string | null;
  employeeCompanyStatus: string | null;
  accountCompanyId: string | null;
  accountCompanyStatus: string | null;
  accountEmail: string | null;
  employeeCode: string | null;
  employeeFirstNameTh: string | null;
  employeeLastNameTh: string | null;
  employeeFirstNameEn: string | null;
  employeeLastNameEn: string | null;
  employeeEmail: string | null;
  companyCode: string | null;
  companyNameTh: string | null;
  companyNameEn: string | null;
  functionCode: string | null;
  functionNameTh: string | null;
  functionNameEn: string | null;
  divisionCode?: string | null;
  divisionNameTh?: string | null;
  divisionNameEn?: string | null;
  departmentCode?: string | null;
  departmentNameTh?: string | null;
  departmentNameEn?: string | null;
  sectionCode?: string | null;
  sectionNameTh?: string | null;
  sectionNameEn?: string | null;
  positionCode: string | null;
  positionNameTh: string | null;
  positionNameEn: string | null;
  levelCode: string | null;
  levelNameTh: string | null;
  levelNameEn: string | null;
  pl: string | null;
  employeeBirthDate?: Date | string | null;
  employeeHireDate?: Date | string | null;
};

export type AuthenticatedPrincipal = {
  userId: string;
  username: string;
  role: RoleCode;
  employeeUserId: string | null;
  employeeId: string | null;
  companyId: string | null;
  email: string | null;
  employeeCode: string | null;
  displayName: string | null;
  displayNameEn?: string | null;
  companyCode: string | null;
  companyName: string | null;
  companyNameEn?: string | null;
  functionCode: string | null;
  functionName: string | null;
  functionNameEn?: string | null;
  divisionCode?: string | null;
  divisionName?: string | null;
  divisionNameEn?: string | null;
  departmentCode?: string | null;
  departmentName?: string | null;
  departmentNameEn?: string | null;
  sectionCode?: string | null;
  sectionName?: string | null;
  sectionNameEn?: string | null;
  positionCode: string | null;
  positionName: string | null;
  positionNameEn?: string | null;
  levelCode: string | null;
  levelName: string | null;
  levelNameEn?: string | null;
  pl: string | null;
  birthDate?: string | null;
  startDate?: string | null;
  hireDate?: string | null;
};
