export type UserModule = "register" | "roadmap" | "request" | "record" | "report";

export const moduleCards: Array<{
  key: UserModule;
  eyebrow: string;
  title: string;
  detail: string;
  metric: string;
}> = [
  {
    key: "register",
    eyebrow: "Register",
    title: "Register Train",
    detail: "Select available courses, submit registration, and let HRD review the request.",
    metric: "3 courses",
  },
  {
    key: "roadmap",
    eyebrow: "Roadmap",
    title: "Training Roadmap",
    detail: "Review the personal development plan and required courses by timeline.",
    metric: "FY2026",
  },
  {
    key: "request",
    eyebrow: "Need",
    title: "Request Training Need",
    detail: "Submit a new training need to HRD Center for review and approval.",
    metric: "2 pending",
  },
  {
    key: "record",
    eyebrow: "Record",
    title: "Training Record",
    detail: "Check training history, accumulated hours, course results, and evidence status.",
    metric: "9 hours",
  },
  {
    key: "report",
    eyebrow: "Report",
    title: "Training Report",
    detail: "Prepare and review employee training reports for HRD follow-up.",
    metric: "Ready",
  },
];

export const availableCourses = [
  {
    id: "PDPA-2026-07",
    title: "Data Privacy Awareness",
    category: "Compliance",
    round: "Round 1 / 2026",
    trainingStatus: "Not trained",
    type: "Mandatory",
    budget: "THB 48,500",
    trainer: "IT Governance",
    owner: "HRD Learning & Development",
    courseOwner: "Center",
    description: "Personal data protection awareness for all employees.",
    date: "15 Jul 2026",
    time: "09:30 - 11:30",
    place: "Online",
    seats: "12 seats",
    status: "Waiting HRD approval",
    duration: "2 hours",
    registrationDeadline: "10 Jul 2026",
    approvalFlow: "Employee > Supervisor > HRD Center",
    targetGroup: "All employees who handle personal data",
    prerequisite: "No prerequisite",
    documents: "E-learning link, attendance log, post-test result",
    contact: "hrd.center@example.invalid",
    remarks: "Post-test score 80% or higher is required for completion.",
  },
  {
    id: "SAFE-2026-08",
    title: "Safety & Compliance Basics",
    category: "Safety",
    round: "Round 2 / 2026",
    trainingStatus: "Registered",
    type: "Compliance",
    budget: "THB 52,000",
    trainer: "Safety Team",
    owner: "Safety & Compliance",
    courseOwner: "Factory",
    description: "Review key safety standards and rules for operational areas.",
    date: "21 Aug 2026",
    time: "10:00 - 12:00",
    place: "Auditorium",
    seats: "8 seats",
    status: "Registered",
    duration: "2 hours",
    registrationDeadline: "14 Aug 2026",
    approvalFlow: "Employee > Supervisor > Factory HR",
    targetGroup: "Production, Engineering, Safety and Environment",
    prerequisite: "Safety orientation completed",
    documents: "Attendance sheet, safety acknowledgement, training record",
    contact: "factory.safety@example.invalid",
    remarks: "Bring employee ID card for on-site attendance confirmation.",
  },
  {
    id: "SERV-2026-09",
    title: "Service Mind for Frontline",
    category: "Soft Skill",
    round: "Round 1 / 2026",
    trainingStatus: "Not trained",
    type: "Core",
    budget: "THB 62,000",
    trainer: "Maliwan P.",
    owner: "Corporate Training",
    courseOwner: "Center",
    description: "Develop service, communication, and coordination skills for frontline teams.",
    date: "8 Sep 2026",
    time: "09:00 - 16:00",
    place: "Training Room B",
    seats: "20 seats",
    status: "Open registration",
    duration: "6 hours",
    registrationDeadline: "1 Sep 2026",
    approvalFlow: "Employee > Supervisor > HRD Center",
    targetGroup: "Frontline service, sales support, and customer-facing employees",
    prerequisite: "No prerequisite",
    documents: "Workshop material, attendance sheet, satisfaction survey",
    contact: "corporate.training@example.invalid",
    remarks: "Workshop includes group practice and service scenario review.",
  },
] as const;

export const employeeCalendarTrainings = [
  {
    date: "2026-07-05",
    title: "5S Refresher",
    shortName: "5S",
    time: "09:00 - 10:30",
    place: "Training Room A",
    status: "Completed",
  },
  {
    date: "2026-07-15",
    title: "Data Privacy Awareness",
    shortName: "PDPA",
    time: "09:30 - 11:30",
    place: "Online",
    status: "Waiting approval",
  },
  {
    date: "2026-07-24",
    title: "Quality Control Basics",
    shortName: "QC",
    time: "13:00 - 16:00",
    place: "Training Room B",
    status: "Planned",
  },
  {
    date: "2026-08-21",
    title: "Safety & Compliance Basics",
    shortName: "Safety",
    time: "10:00 - 12:00",
    place: "Auditorium",
    status: "Registered",
  },
  {
    date: "2026-09-08",
    title: "Service Mind for Frontline",
    shortName: "Service",
    time: "09:00 - 16:00",
    place: "Training Room B",
    status: "Open registration",
  },
  {
    date: "2027-01-14",
    title: "Annual Compliance Refresh",
    shortName: "Annual",
    time: "09:00 - 12:00",
    place: "Online",
    status: "Planned",
  },
] as const;

export const roadmapItems = [
  {
    code: "PDPA-2026",
    title: "Data Privacy Awareness",
    category: "Mandatory",
    detail: "Mandatory course for every employee to understand personal data handling.",
    round: "Round 1 / 2026",
    trainingStatus: "Not trained",
    type: "Mandatory",
    budget: "THB 48,500",
    trainer: "IT Governance",
    owner: "HRD Learning & Development",
    courseOwner: "Center",
    targetFunctions: ["All"],
    targetPositions: ["All"],
    targetLevels: ["All"],
    targetCompanies: ["All"],
    due: "15 Jul 2026",
    status: "Registration recommended",
    action: "Register",
    priority: "High",
  },
  {
    code: "SAFE-2026",
    title: "Safety & Compliance Basics",
    category: "Safety",
    detail: "Recommended safety compliance refresh for operational employees.",
    round: "Round 2 / 2026",
    trainingStatus: "Registered",
    type: "Compliance",
    budget: "THB 52,000",
    trainer: "Safety Team",
    owner: "Safety & Compliance",
    courseOwner: "Factory",
    targetFunctions: ["Production", "Engineering and Maintenance", "Safety and Environment"],
    targetPositions: ["Operator", "Foreman", "Leader", "Staff"],
    targetLevels: ["Operator Level", "Development Operator", "L1", "L2", "L3"],
    targetCompanies: ["SATI", "ATFB", "TEP", "ATA", "NIC", "SNF"],
    due: "21 Aug 2026",
    status: "Registered",
    action: "View detail",
    priority: "Medium",
  },
  {
    code: "QC-2026",
    title: "Quality Control Basics",
    category: "Role Skill",
    detail: "Recommended course for Production employees to improve quality inspection skills.",
    round: "Round 1 / 2026",
    trainingStatus: "Not trained",
    type: "Role Skill",
    budget: "THB 44,500",
    trainer: "QA Department",
    owner: "HRD Learning & Development",
    courseOwner: "Center",
    targetFunctions: ["Production", "Quality"],
    targetPositions: ["Operator", "Engineer", "Leader"],
    targetLevels: ["Operator Level", "Development Operator", "L1", "L2", "L3"],
    targetCompanies: ["All"],
    due: "24 Sep 2026",
    status: "Ready to register",
    action: "Register",
    priority: "Recommend",
  },
] as const;

export const requestStatuses = [
  { title: "Submit training need to HRD Center", owner: "Employee", status: "Done" },
  { title: "HRD Center review and approval", owner: "HRD", status: "In review" },
  { title: "Training approval result published", owner: "System", status: "Pending" },
] as const;

export const history = [
  { course: "Orientation Program", date: "12 May 2026", hours: "6", result: "Completed" },
  { course: "5S Awareness", date: "22 Jun 2026", hours: "3", result: "Completed" },
  { course: "Data Privacy Awareness", date: "15 Jul 2026", hours: "2", result: "Pending approval" },
] as const;

export const recordCourses = [
  {
    course: "Orientation Program",
    date: "12 May 2026",
    year: "2026",
    month: "05",
    result: "Passed",
    assessment: "No assessment required",
    action: "Completed",
  },
  {
    course: "5S Awareness",
    date: "22 Jun 2026",
    year: "2026",
    month: "06",
    result: "Not passed",
    assessment: "Pre/post test required",
    action: "Retake test",
  },
  {
    course: "Data Privacy Awareness",
    date: "15 Jul 2026",
    year: "2026",
    month: "07",
    result: "Pending",
    assessment: "Waiting HRD approval",
    action: "Follow up",
  },
] as const;

export const externalRecordRequests = [
  {
    course: "Forklift Safety Training",
    source: "External training",
    status: "Submitted to HRD for verification",
  },
  {
    course: "Basic Welding Skill",
    source: "Previous workplace record",
    status: "Waiting certification",
  },
] as const;
